language: python

python:
  - "3.5"

before_install:
  - npm install -g sloc

install:
  - pip install -r requirements.txt

script:
  - python tests.py

after_success:
  - "openssl aes-256-cbc -K $encrypted_5cf2ad958087_key -iv \
    $encrypted_5cf2ad958087_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d"
  - chmod 600 ~/.ssh/id_rsa
  - "cp .travis/known_hosts ~/.ssh/known_hosts"
  - git push -f dokku@192.241.178.63:git-loc-server master
